# Python Numérico

## El paquete NumPy

### Operaciones con arrays


Las **funciones universales** (`ufunc`) operan sobre arrays de NumPy elemento a elemento y siguiendo cirtas reglas (_broadcasting_):
* Funciones matemáticas: `sin`, `cos`, `sqrt`, `exp`
* Operaciones lógicas <, >, ==, ...
* Funciones lógicas: `all`, `any`, `isnan`, `allclose`

In [1]:
import numpy as np

In [10]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [11]:
a = np.arange(2 * 3)
a

array([0, 1, 2, 3, 4, 5])

In [3]:
a = a.reshape(2, 3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [4]:
np.sqrt(a)

array([[0.        , 1.        , 1.41421356],
       [1.73205081, 2.        , 2.23606798]])

In [5]:
np.arange(-3, 3)

array([-3, -2, -1,  0,  1,  2])

In [6]:
np.sqrt(np.arange(-3, 3))

/tmp/ipykernel_29297/2991463662.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(np.arange(-3, 3))


array([       nan,        nan,        nan, 0.        , 1.        ,
       1.41421356])

In [7]:
np.arange(-3, 3).astype(complex)

array([-3.+0.j, -2.+0.j, -1.+0.j,  0.+0.j,  1.+0.j,  2.+0.j])

In [8]:
np.sqrt(_)

array([0.        +1.73205081j, 0.        +1.41421356j,
       0.        +1.j        , 0.        +0.j        ,
       1.        +0.j        , 1.41421356+0.j        ])

In [13]:
a = np.arange(6)
b = np.ones(6).astype(int)
a, b

(array([0, 1, 2, 3, 4, 5]), array([1, 1, 1, 1, 1, 1]))

In [14]:
# Se hace una comparación vectorizada
a < b

array([ True, False, False, False, False, False])

In [15]:
# Verifica si hay algún valor True en el arreglo
np.any(a < b) 

True

In [16]:
# Verifica si todos son verdaderos
np.all(a < b)

False

Los números de punto flotante no pueden ser comparados automáticamente como los enteros debido a la precisión de su representación. Para comparar arrays de floats se utiliza `isclose()` o `allclose()` especificando una tolerancia para la comparación:

In [19]:
a = np.arange(6).astype(float)
b = np.ones(6)
a, b

(array([0., 1., 2., 3., 4., 5.]), array([1., 1., 1., 1., 1., 1.]))

In [20]:
np.isclose(a, b, rtol=1e-6)

array([False,  True, False, False, False, False])

In [21]:
np.allclose(a,b, rtol=1e-6)

False

### Ejercicios

#### Ejercicio 1:

1. Crear un array $z1$ de 3x4 lleno de ceros tipo entero
2. Crear un array $z2$ de 3x4 lleno de ceros excepto la primera fila que serán todos unos
3. Crear un array $z3$ de 3x4 lleno de ceros excepto la última fila que será de rango entre 5 y 8

In [40]:
z1 = np.zeros((3,4)).astype(int)
z1

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [46]:
z2 = np.zeros((3, 4))
z2

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [47]:
z2[0]

array([ 0.,  0.,  0.,  0.])

In [48]:
z2[0 , :]

array([ 0.,  0.,  0.,  0.])

In [52]:
z2[0, :] = np.ones(4)
z2

array([[ 1.,  1.,  1.,  1.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [28]:
np.ones(4)

array([ 1.,  1.,  1.,  1.])

**Nota:** Observar que puede hacerse la asignación vectorizada también. La operación siguiente se expande a la forma de la matriz.

In [54]:
z2[1, :] = 1
z2

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 0.,  0.,  0.,  0.]])

In [57]:
z3 = np.zeros((3,4))
z3

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [59]:
z3[2, :]=np.array(range(5,9))
z3

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 5.,  6.,  7.,  8.]])

### Arreglos básicos

Se pueden crear arreglos con la función `arange()`. La instancia `arange(n)` genera $n$ elementos iniciando desde $0$ hasta $n-1$. La instancia `arange(a, n)` genera $n-a$ elementos iniciando desde $a$ hasta $n-1$. La instancia `arange(a,n,s)` genera $(n-a)/s + 1$ elementos.

In [301]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [303]:
np.arange(-1, 7)

array([-1,  0,  1,  2,  3,  4,  5,  6])

In [304]:
np.arange(2, 10,2)

array([2, 4, 6, 8])

In [299]:
np.arange(3, 10, 3)

array([3, 6, 9])

## Indexado

Python crea índices de un array enumerándolos en ambos sentidos. De izquierda a derecha los índices son positivos e inician desde $0$, de derecha a izquierda los índices son negativos e inician desde $-1$.

En el sentido izquierda a derecha, para $n$ elementos en el array, los índices serán desde $0,...,n-1$.


In [445]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [398]:
a[1]   #Elemento con índice 1

1

In [399]:
a[-1]  # El último elemento

5

In [400]:
a[:]  # Recorre todos los elementos

array([0, 1, 2, 3, 4, 5])

In [401]:
a[1:3]  # Dado a, b se especifica el intervalo [a, b)

array([1, 2])

In [129]:
a[:]  # Recorre todos los elementos

array([0, 1, 2, 3, 4, 5])

In [132]:
a[:2]  # Recorre del índice 0 al 1

array([0, 1])

In [133]:
a[2:] # Recorre desde el índice 2 hasta el último  indice

array([2, 3, 4, 5])

In [139]:
a[2:-1] # Recorre desde el índice 2 hasta el penúltimo índice

array([2, 3, 4])

In [143]:
a

array([0, 1, 2, 3, 4, 5])

In [158]:
a[0:6:2]   # Recorre todos los índices de 2 en 2

array([0, 2, 4])

In [157]:
a[:6:2]   # Recorre todos los índices de 2 en 2

array([0, 2, 4])

In [141]:
a[::2] # Recorre todos los índices de 2 en 2

array([0, 2, 4])

In [156]:
a[1:6:2]  # Recorre del índice 1 al 5 de 2 en 2   

array([1, 3, 5])

In [149]:
a[::3] # Recorre todos los índices de 3 en 3

array([0, 3])

Slicing con índices negativos

In [22]:
# aplica el intervalo [a,b)
a[-7:-1]

array([0., 1., 2., 3., 4.])

In [358]:
# elementos con índices desde -10 hasta el -4
# tomados de 2 en 2
a[-10:-5:2]

array([1, 3, 5])

In [326]:
# todos los elementos
# referiremos a los elementos con índices -10 hasta -1
a[:]


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [350]:
# equivalente al anterior
# recorre desde el primer elemento del array hasta el final
a[-10:]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [354]:
# desde él último elemento hasta el final
a[-1:]

array([10])

In [359]:
# recorre desde el inicio hasta el índice -4
# intervalo [-10, -3)
a[:-3]

array([1, 2, 3, 4, 5, 6, 7])

In [363]:
# desde el inicio hasta el primer elemento
a[:-9]

array([1])

In [343]:
# elementos con índices desde -10 hasta el -4
# tomados de 2 en 2
a[-10:-3:2]

array([1, 3, 5, 7])

In [344]:
# equivalente que el anterior
a[:-3:2]

array([1, 3, 5, 7])

In [345]:
# Recorre todos los elememtos tomando de 2 en 2
a[::2]

array([1, 3, 5, 7, 9])

In [347]:
# todos los elementos
# tomados de 3 en 3
a[-10::3]

array([ 1,  4,  7, 10])

In [352]:
# equivalente al anterior
a[::3]

array([ 1,  4,  7, 10])

## Arreglos bidimensionales

Un arreglo bidimensional puede entenderse como un array de arrays unidimensionales $[a_0, a_1, a_2,...,a_n]$ donde cada $a_i$ tiene $m$ elementos.

In [24]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [25]:
# array a0 elemento con índice 1
a[0,1]  # Los índices comienzan en cero

1

In [26]:
# Array a0 y todos sus elementos
a[0, :]

array([0, 1, 2, 3])

In [27]:
# de todos los arrays se toman los elemntos
# con índice 2.
a[:, 2]

array([ 2,  6, 10])

In [28]:
# array a0, a1
a[0 : 2 ]

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [29]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [30]:
# de los arrays a0, a1 se toman sus
# elementos con índice 1 
a[0 : 2 , 1]

array([1, 5])

In [31]:
# de los arrays a0, a1 se toman
# los elementos con índices 1 y 2
a[0:2 , 1:3]

array([[1, 2],
       [5, 6]])

In [32]:
a[0::]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [33]:
a[0::, 1]

array([1, 5, 9])

In [34]:
a[0::, 1:3]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]])

In [35]:
a[0:: , 0:: ]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [36]:
np.zeros?

In [37]:
a = np.zeros((3, 4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [38]:
a[0, :] = np.ones(4)   # Cambia a 1,s el primer renglón
a

array([[1., 1., 1., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [39]:
a[2, :] = 1   # Es equivalente a la anterior
              # La operación se expande
a

array([[1., 1., 1., 1.],
       [0., 0., 0., 0.],
       [1., 1., 1., 1.]])

In [40]:
a[2]   # Denota todo el renglón con índice 2

array([1., 1., 1., 1.])

In [41]:
a[-2]  # Denota el penúltimo renglón

array([0., 0., 0., 0.])

In [42]:
b = np.zeros((3, 4))

In [43]:
b[-1] = np.arange(5, 9)
b

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [5., 6., 7., 8.]])

In [44]:
v = np.ones(10)
v

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [45]:
v[::2] = 2
v

array([2., 1., 2., 1., 2., 1., 2., 1., 2., 1.])

In [46]:
tablero = np.zeros((8,8))
tablero

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [47]:
tablero[1::2, ::2] = 1
tablero

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

In [48]:
tablero[::2, 1::2] = 1
tablero

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])