# Python Numérico

## El paquete NumPy

Python está organizado en módulos que son archivos con extensión .py que contienen funciones, variables y otros objetos; los paquetes son conjuntos de módulos. Cuando se quiere utilizar objetos que están definidos en un módulo se tiene que _importarlo_ y una vez hecho esto utilizar el operado . para descender en la jerarquía de paquetes y acceder al objeto necesitado.  

In [1]:
# importacion de NumPy
import numpy


Acceso a la función `norm` que calcula la norma (módulo) de un array:

In [2]:
numpy.linalg.norm

<function numpy.linalg.norm(x, ord=None, axis=None, keepdims=False)>

La función `norm` está dentro del paquete `linalg` que a su vez está dentro del paquete `numpy`

La convención para importar `NumPy` siempre es la siguiente:

In [3]:
import numpy as np

Se crea un alias del paquete `NumPy` de nombre `np`. Esta forma de organizar las funciones por medio de paquetes (espacio de nombre) ayuda a tener una legibilidad en el código y evitar ambigüedades explícito de  

Es posible encontrar ayuda de cierto tema con la función `lookfor()`

In [4]:
np.lookfor('solve')

Search results for 'solve'
--------------------------
numpy.linalg.solve
    Solve a linear matrix equation, or system of linear scalar equations.
numpy.linalg.lstsq
    Return the least-squares solution to a linear matrix equation.
numpy.linalg.tensorsolve
    Solve the tensor equation ``a x = b`` for x.
numpy.nditer.close
    close()
numpy.array_api.linalg.solve
    Array API compatible wrapper for :py:func:`np.linalg.solve <numpy.linalg.solve>`.
numpy.linalg._umath_linalg.solve
    solve the system a x = b, on the last two dimensions, broadcast to the rest.
numpy.linalg._umath_linalg.solve1
    solve the system a x = b, for b being a vector, broadcast in the outer dimensions.
numpy.distutils.misc_util.njoin
    Join two or more pathname components +
numpy.distutils.misc_util.minrelpath
    Resolve `..` and '.' from path.
numpy.AxisError
    Axis supplied was invalid.
numpy.shares_memory
    Determine if two arrays share memory.
numpy.linalg.eig
    Compute the eigenvalues and right 

## Constantes y funciones matemáticas

In [5]:
np.e

2.718281828459045

In [6]:
np.pi

3.141592653589793

In [7]:
np.log(2)arrays

0.6931471805599453

## Arrays de NumPy

Un `array`de NumPy es una colección de `N` elementos de la misma forma que una secuencia (lista), tienen las mismas propiedades que éstas y algunas más. Para crear un array, la forma más directa es pasar una secuencia a la función `np.array()`

In [8]:
np.array([1, 2, 3])

array([1, 2, 3])

Para acceder al tipo del array se utiliza el atributo `dtype`

In [9]:
np.array([1, 2, 3]).dtype

dtype('int64')

Los arrays de NumPy son homogéneos, es decir, sus elementos son del mismo tipo. Si se agregan objetos de diferente tipo a `np.array` se promueven al objeto con la mayor con mayor información. 

In [10]:
np.array([1, 2, 3.]).dtype

dtype('float64')

In [11]:
np.array([1, 2, '3'])

array(['1', '2', '3'], dtype='<U21')

NumPy intentará construir un array con el tipo adecuado aunque es posible forzar el tipo del array

In [12]:
np.array([1, 2, 3], dtype=float)

array([1., 2., 3.])

In [13]:
np.array([1, 2, 3], dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

Otra forma de convertir el tipo de un array es usando el método `.astype`

In [14]:
a = np.array([1., 2., 3.])
print(a.dtype)

float64


In [15]:
a.astype(int)

array([1, 2, 3])

## Vectorización

La importancia de usar arreglos (arrays) de NumPy consiste en la eficiencia al hacer cálculos:
* Se **vectorizan** las operaciones sobre los arreglos
* Los bucles se ejecutan en Python, los cálculos con vectores en C
* Las operaciones entre arrays de NumPy se realizan elemento a elemento

**Ejemplo:** Vamos a crear dos matrices $a_{ij}$ y $b_{ij}$  y se va a calcular la suma $c_{ij} = a_{ij} + b_{ij}$

In [17]:
N,M = 100, 100
a = np.empty(10000).reshape(N, M)
b = np.random.rand(10000).reshape(N, M)
c = np.random.rand(10000).reshape(N, M)

In [19]:
%%timeit
for i in range(N):   # Se usan bucles
    for j in range (M):
        a[i,j] = b[i,j] + c[i,j]

2.58 ms ± 38.5 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [20]:
%%timeit
a = b + c   # Se vectoriza la operación

3.34 µs ± 51.4 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


## Indexado de arryas

El indexado consiste en seleccionar uno o más elementos de un arreglo. Este es uno de los conceptos básicos al momento de trabajar con un los arreglos. Existen distintas técnicas de indexado que potencian el manejo de los arreglos.

In [21]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
a[0][0]

1

In [23]:
a[0,0]

1

In [24]:
a[0:2, 0:2]

array([[1, 2],
       [4, 5]])

Los índices se indican entre corchetes justo después del nombre del arreglo, recordemos que los índices en Python inician en 0. Si en un array de dos dimensiones se recupera el primer elemento, se obtendrá el primer renglón

In [25]:
a[0]

array([1, 2, 3])

## Creación de arrays

Existen métodos muy variados para crear arrays:
* A partir de datos existentes: `array`, `copy`
* Unos y Ceros: `empty`, `ones`, `zeros`, `*_like`
* Rangos: `arange`, `linspace`, `logspace`, `meshgrid`
* Aleatorios: `rand`, `randn`


### Unos y Ceros

* `empty(shape)` crea un array con "basura", equivalente a  no inicializarlo, es ligeramente más rápido que `zeros` y `unos`
* `eye(N, N=None, k=0)` crea un array con unos en una diagonal y ceros en el resto
* `identity(n)` devuelve la matriz identidad
* Las funciones `*_like()` constituyen arrays con el mismo tamaño que uno dado

In [26]:
np.empty((3,4))

array([[-0.        , -0.10527243, -0.        , -0.36204275],
       [ 0.        ,  0.60548125, -0.        , -0.92385342],
       [-0.        , -0.18805521,  0.        ,  0.07267947]])

In [27]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [28]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [29]:
np.identity(5).astype(int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [30]:
i3 = np.identity(3)
i3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [31]:
i3.shape

(3, 3)

In [32]:
np.ones(i3.shape)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [33]:
np.ones_like(i3)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### Rangos
* `linspace(start, stop, num=10)` devuelve números equiespaciados dentro de un intervalo
* `logspace(start, stop, num=10` devuelve números equiespaciados según una escala logarítmica
* `meshgrid(x1, x2, ...)` devuelve matrices de n-coordenadas

In [34]:
np.linspace(0, 1, num=10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [35]:
np.logspace(0, 3, num=10, base=10)

array([   1.        ,    2.15443469,    4.64158883,   10.        ,
         21.5443469 ,   46.41588834,  100.        ,  215.443469  ,
        464.15888336, 1000.        ])

In [36]:
x = np.linspace(0, 1, num=5)
y = np.linspace(0, 1, num=5)

xx, yy = np.meshgrid(x, y)

In [78]:
xx, yy

(array([[ 0.  ,  0.25,  0.5 ,  0.75,  1.  ],
        [ 0.  ,  0.25,  0.5 ,  0.75,  1.  ],
        [ 0.  ,  0.25,  0.5 ,  0.75,  1.  ],
        [ 0.  ,  0.25,  0.5 ,  0.75,  1.  ],
        [ 0.  ,  0.25,  0.5 ,  0.75,  1.  ]]),
 array([[ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
        [ 0.25,  0.25,  0.25,  0.25,  0.25],
        [ 0.5 ,  0.5 ,  0.5 ,  0.5 ,  0.5 ],
        [ 0.75,  0.75,  0.75,  0.75,  0.75],
        [ 1.  ,  1.  ,  1.  ,  1.  ,  1.  ]]))