<img src="img/julia.png" width=150 height=150 />

# Introducción a Julia

Julia lo puedes descargar desde https://julialang.org

Para Junio de 2021, la versión más reciente de Julia, es la v1.9.1

## ¿Realmente necesitamos aprender otro lenguaje?

El problema de los dos lenguajes.

En primer lugar, al elegir un lenguaje se considera la facilidad de aprendizaje, la generación de código rápidamente, esto es la **productividad** (_productive_ o _high-level languages_) que ofrece el lenguaje: python, ruby, matlab
En segundo lugar, en diversos problemas a tratar es indispensable considerar  el **rendimiento** del lenguaje de programación (_performance_ o _lower-level languages_) y la generación del código máquina eficiente: Fortran, C, C++. En general un lenguaje es atractivo si es productivo, sin embargo su rendimiento no es óptimo y viceversa; por tanto, la elección de productividad o rendimiento dependerá de las necesidades particulares del problema a resolver.

Adicional a lo anterior la **generalidad** del lenguaje, esto es tomar en cuenta si se trata de un lenguaje de propósito genenal (_general purpose language_) o de dominio específico (_domain-specific language_). Es posible generar código eficiente y rápido de manera sencilla si se trabaja cn lenguajes de dominio específico o con librerías especiales sin embargo el alcance (_scope_) de dichas herramientas será un tanto limitado.

Así, para lograr la productividad, rendimiento y generalidad ( _Productivity vs Performance vs Generality_) es necesario utilizar dos lenguajes. El prototipado de las soluciones se realiza por medio de un lenguaje de alto nivel como Python o MATLAB lo que proporciona una prueba de concepto rápidamente; una vez hecho lo anterior, se realiza la traducción del protototipo a otro lenguaje como C o C++ para realizar los cálculos de manera eficiente.

Evitar el uso de dos lenguajes de programación es la razón primordial de Julia.


El lema de Julia es:

> "looks like **Python**, feels like **Lisp**, runs like **C**"

lo cual puede entenderse en el sentido que Julia ofrece productividad, generalidad y **rendimiento**.

### ¿Por qué elegir Julia sobre otros lenguajes de programación?

### Ventajas de Julia

- Es interpretado
- Es un lenguaje de alto nivel, fácil de aprender
- Diseñado para que sea sencillo desde el comienzo
- Es veloz (~2-3 x la velocidad de C)
- Tiene un sofisticado sistema de tipos de datos
- Sin embargo no es necesario hablar de tipos siempre
- Tiene _despacho múltiple_ de funciones especializado en el tipo de sus argumentos
- Tiene un sofisticado empleo de _metaprogramación_(macros) para la generación de código
- La mayoría de las bibliotecas están implementadas en Julia puro
- Evita el problema del segundo lenguaje: Python, R, Matlab son fáciles de aprender y se logran desarrollos rápidos, sin embargo tienen ejeccuicones lentas, entonces es necesario cambiar ciertas partes del código a C, C++ o Fortran
- Los propios usuarios de Julia son sus desarrolladores

## Recursos

* Discourse: https://discourse.julialang.org Grupo de discusión sobre Julia
* Github: https://github.com/JuliaLang/julia Código puro
* JuliaWebPage: https://julialang.org/learning/ Recursos variados: tutoriales en video y escritos, libros, MOOCS, clases de cómputo cientifico con julia
* JuliaAcademy: https://juliaacademy.com/
* Github de Jane Herriman: [xorJane](https://github.com/xorJane)
* Github de Huda Nassar:[nassarhuda](https://github.com/nassarhuda)
* Github de David Sanders:[dpsanders](https://github.com/dpsanders)

### Uso de Julia
- Desde el REPL (Read-Eval-Print-Loop): `$julia`
- Invocando  `IJulia` (Interface de Python interactivo con kernel de Julia): `$ ipython notebook --profile julia`
- Dentro de un Ambiente de Desarrollo integrado, por ejemplo VS-Code, Atom, Jupyter, Colab, Cocalc, [Pluto](https://github.com/fonsp/Pluto.jl)

## 1. REPL, sintáxis básica, variables y tipos de datos

### Modos de REPL

In [1]:
? pwd # solicita ayuda

search: pwd powermod



```
pwd() -> AbstractString
```

Get the current working directory.

See also: [`cd`](@ref), [`tempdir`](@ref).

# Examples

```julia-repl
julia> pwd()
"/home/JuliaUser"

julia> cd("/home/JuliaUser/Projects/julia")

julia> pwd()
"/home/JuliaUser/Projects/julia"
```


In [3]:
pwd() # muestra la ruta actual

"/home/oscar/Escritorio/tutorial-julia-enc2021"

In [9]:
; ls

ENC2021-N1-IntroJulia.ipynb
img
S1-IntroJulia.ipynb
S2-IntroJulia.ipynb
S3-ObjetosEstructuras.ipynb
S4-JuliaEsRapido.ipynb
S5-CodigoEficiente.ipynb
S6-OtrasFuncionalidadesJulia.ipynb
S7-EjemploNumerico.ipynb
S8-OperacionesVectorizadas.ipynb


`;` cambia al prompt del shell para ejecutar comandos 

 ### Variables y cálculos aritméticos

In [ ]:
3

In [ ]:
3 + 2

In [ ]:
3 * 5 

In [ ]:
3 - 1; #Ejecución silenciosa

In [ ]:
x = 3

Podemos ingresar en el código notación de Latex, usando sustitución con TAB:  `\alpha<TAB>`

In [ ]:
α

In [ ]:
β

In [9]:
α = 3

3

In [10]:
ϵ = 10

10

In [11]:
print("α = ", α)

α = 3

### Sustitución de variables
Los valores de las variables pueden ser sustituidos por cadenas de caracteres de una manera sencilla usando el operador `$`

In [14]:
name = "Oscar"
greeting = "Hello, $name"
println(greeting)

Hello, Oscar


In [15]:
μ = 3
println("The sine of $μ is $(sin(μ))")

The sine of 3 is 0.1411200080598672


### Operadores matemáticos

In [16]:
suma = 3 + 7

10

In [17]:
diferencia = 10 - 3

7

In [18]:
producto = 3 * 2

6

In [19]:
division = 10 / 10

1.0

In [20]:
division2 = div(5, 2)

2

In [21]:
potencia = 2 ^ 3

8

In [22]:
modulo = 10 % 3

1

###  Tipos de datos numéricos

Julia contiene un amplio conjunto de tipos de datos:
- Los tipos de datos numéricos pueden tener diferente precisión
- Actualmente, al realizar cálculos aritméticos el tipo de dato resultante es promovido al tipo de dato del equipo de cómputo.
- Al escribir `Float<TAB>` o `Int<TAB>` resultara en una lista desplegable de tipos a elegir.

In [11]:
Float16

Float16

In [12]:
Int64

Int64

In [13]:
a = Int8(1)
b = Int8(2)
a + b

3

In [28]:
typeof(ans)

Int8

In [29]:
a = Int(1e5)

100000

In [30]:
typeof(a)

Int64

In [31]:
typeof(3 * a)

Int64

Julia esta diseñado de tal forma que provee una jerarquía de tipos de datos la cual define conjuntos y subconjuntos de tipos:

In [32]:
a = 5

5

In [33]:
typeof(a)

Int64

In [34]:
supertype(Int64)

Signed

In [35]:
supertype(Signed)

Integer

In [36]:
supertype(Integer)

Real

In [37]:
subtypes(Real)

4-element Vector{Any}:
 AbstractFloat
 AbstractIrrational
 Integer
 Rational

In [38]:
subtypes(Integer)

3-element Vector{Any}:
 Bool
 Signed
 Unsigned

In [39]:
subtypes(Signed)

6-element Vector{Any}:
 BigInt
 Int128
 Int16
 Int32
 Int64
 Int8

Bajo esta jerarquía de tipos se pueden caracterizar dos grupos de datos:
- Dato **Abstracto** es algo como `Real`
- Dato **Concreto** es algo como `Int64`


In [40]:
isconcretetype(Float64)

true

In [41]:
@show isconcretetype(Real);

isconcretetype(Real) = false


In [42]:
@show isabstracttype(Real);

isabstracttype(Real) = true


El siguiente código muestra la jerarquía de tipos de datos de Julia

In [29]:
function _show_subtype_tree(mytype, printlevel)
    allsubtypes = subtypes(mytype)
    for cursubtype in allsubtypes
        print("\t"^printlevel)
        println("|___",cursubtype)
        printlevel += 1
        _show_subtype_tree(cursubtype, printlevel)
        printlevel -= 1
    end
end
function show_type_tree(T)
    println(T)
    _show_subtype_tree(T,0)
end
show_type_tree(Number)

Number
|___Complex
|___Real
	|___AbstractFloat
		|___BigFloat
		|___Float16
		|___Float32
		|___Float64
	|___AbstractIrrational
		|___Irrational
	|___Integer
		|___Bool
		|___Signed
			|___BigInt
			|___Int128
			|___Int16
			|___Int32
			|___Int64
			|___Int8
		|___Unsigned
			|___UInt128
			|___UInt16
			|___UInt32
			|___UInt64
			|___UInt8
	|___Rational


### Aritmética de precisión arbitraria
Es posible obtener enteros o flotantes de precisión arbitrario por medio de los tipos `BigInt` y `BigFloat`.
La función `Big` convierte un número a el correspontiente tipo `Big`. Julia envuelve (wraps) la biblioteca *GNU Multiple Precision Arithmetic* [GMP](https://gmplib.org/)

In [44]:
10

10

In [45]:
typeof(10)

Int64

In [46]:
big(10)

10

In [47]:
typeof(ans)

BigInt

In [48]:
10^5

100000

In [49]:
10^10

10000000000

In [50]:
10^15 

1000000000000000

In [51]:
10^19 # error

-8446744073709551616

In [53]:
bten = big(10)

10

In [54]:
bten ^ 19

10000000000000000000

In [55]:
typeof(ans)

BigInt

In [56]:
typemax(Int64)

9223372036854775807

In [57]:
typemin(Int64)

-9223372036854775808

### Números complejos
Los números complejos utilizan `im` para la parte imaginaria

In [58]:
a = 7
c = (1 + 3.5im) * a

7.0 + 24.5im

In [59]:
typeof(c)

ComplexF64 (alias for Complex{Float64})

In [60]:
c.re, c.im

(7.0, 24.5)

In [61]:
c.re

7.0

In [62]:
conj(c) # conj is a funciton that returns the conjugate of a complex

7.0 - 24.5im

### Números racionales
Los números racionales puden ser construidos en Julia al usar el operador `//`

In [63]:
3//4

3//4

In [64]:
typeof(ans)

Rational{Int64}

In [65]:
3//4 + 5//6 

19//12

### Cadenas

In [67]:
s1 = "Esto es un string."

"Esto es un string."

In [68]:
s2 = """Esto es un string."""

"Esto es un string."

In [15]:
"Aquí hay un "error" de cadenas"

LoadError: syntax: cannot juxtapose string literal

In [16]:
"""Aquí no hay un "error" de cadenas"""

"Aquí no hay un \"error\" de cadenas"

In [17]:
""" Esto es una multi-string
multi-string
multi-string
"""

" Esto es una multi-string\nmulti-string\nmulti-string\n"

**Nota:** Las comillas simples `' '` denotan un caracter, no una cadena. 

In [72]:
typeof('a')

Char

In [73]:
typeof("a")

String

### Concatenación de cadenas

In [74]:
nombre = "Julia "
apellido =  "Programming"

"Programming"

In [75]:
# usando la función string
string(nombre, apellido)

"Julia Programming"

In [76]:
# usando el operador *
nombre * apellido

"Julia Programming"

Una cadena puede repetirse usando la función `repeat()`, o con los operadores `^` y `*`.

In [77]:
repeat(nombre, 5)

"Julia Julia Julia Julia Julia "

In [78]:
nombre ^ 5

"Julia Julia Julia Julia Julia "

## 2. Control de flujo

### Condicionales

La sintáxis para una expresión condicional incluye la palabra reservada `if` y es:
```julia
if condicion 1
    opcion 1
elseif condicion 2
    opcion 2
else
    opcion 3
end
    ```

La función `isequal()` es equivalente al operador `==`.

Una forma alternativa de escribir un condicional es por medio de **operadores ternarios**:
```julia
a ? b : c
```
lo que equivale a:
```julia
if a
    b
else
    c
end
```



In [82]:
x = 3
y = 100

100

In [83]:
(x > y) ? x : y

100

### Short-circuit 

El operador `&` hace la evaluación de dos expresiones booleanas por medio de la operación `AND`. El operador `&&` hace la misma evaluación pero en caso que la primera evaluación sea `false` no hace la segunda evaluación. 

In [18]:
# operador para AND
false & true

false

In [21]:
false & (println("Hola"); true)

Hola


false

In [22]:
# short-circuit operator para AND
false && true

false

In [23]:
false && (println("Hola"); true)

false

In [24]:
true && (println("Hola"); false)

Hola


false

Por otra parte, el operador `&&` no requiere que la segunda expresión devuelva el valor de `true` o `false`, veamos un ejemplo:

In [28]:
x = 5
(x > 0) && error("x no puede ser mayor que 0")

ErrorException: x no puede ser mayor que 0

In [26]:
(x < 0) && (error("x no puede ser mayor que 0"); true)

false

De forma similar, el operador `||` es utilizado para hacer la evaluación de corto circuito de la operación `OR`. Dado un `true` en la primera expresión no se evalúa la segunda.

In [90]:
# operador para OR
true | false

true

In [91]:
# short circuit operador para OR 
true || false

true

In [92]:
true || println("hola")

true

In [93]:
false || println("hola")

hola


### Ciclo While 

La sintáxis para un ciclo `while` es:
```julia
while condicion
    cuerpo del ciclo
end
    ```

In [30]:
n = 0
while n < 10
    n += 1
    println(n)
end
n

1
2
3
4
5
6
7
8
9
10


10

Podemos utlizar el `while` para iterar sobre un objeto iterable (listas, tuplas)

In [95]:
misamigos = ["marco", "raul", "hector", "victor"]

i = 1
while i <= length(misamigos)
    amigo = misamigos[i]
    println("Hola $amigo, ¿qué tal estás?")
    i += 1
end

Hola marco, ¿qué tal estás?
Hola raul, ¿qué tal estás?
Hola hector, ¿qué tal estás?
Hola victor, ¿qué tal estás?


### Ciclo For 

La sintáxis para un ciclo `for` es:
```julia
for var in iterable
    cuerpo del ciclo
end
    ```

In [96]:
for n in 1:10
    println(n)
end

1
2
3
4
5
6
7
8
9
10


In [97]:
myfriends = ["Carlos", "Raul", "Edmundo", "Giovanni", "Fabian"]
for name in myfriends
    println("Hola $name, ¿qué tal?")
end

Hola Carlos, ¿qué tal?
Hola Raul, ¿qué tal?
Hola Edmundo, ¿qué tal?
Hola Giovanni, ¿qué tal?
Hola Fabian, ¿qué tal?


## 3. Estructuras de datos

Las estructuras de datos funcionan como colectores de elementos, las estructuras básicas son:
* **Tuplas:** ordenadas, inmutables
* **Diccionarios:** desordenadas (*unordered*), mutables, similares a las _hash tables_ 
* **Arreglos:** ordenadas, mutables

### Tuplas

Se construyen encerrando entre `()` una colección ordenada de elementos.

La sintaxis es:

   `(item1, item2, ...)`

Las tuplas son inmutables. Una vez que son creadas no pueden ser modificadas.

In [98]:
mismascotas = ("alpha", "yanina", "renata")

("alpha", "yanina", "renata")

In [99]:
# indexado
mismascotas[1]

"alpha"

In [100]:
mismascotas[2]

"yanina"

In [101]:
# error
mismascotas[0]

LoadError: BoundsError: attempt to access Tuple{String, String, String} at index [0]

**Nota:** El indexado en Julia inicia en 1

In [102]:
mismascotas[1] = "camaleón"

LoadError: MethodError: no method matching setindex!(::Tuple{String, String, String}, ::String, ::Int64)

Las tuplas son **objetos inmutables**, una vez que son creadas no pueden ser modificadas.

### Named Tuples

Es un nuevo tipo de tupla implementado en la versión 1.0. Cada elemento de la tupla tiene un nombre al cual se le asigna un valor.

La sintaxis de este tipo de tupla es:

    `(name1 = item1, name2 = item2, ...)`.

In [103]:
mismascotas_nt = (perro = "alpha", gato = "yanina", tortuga = "renata")

(perro = "alpha", gato = "yanina", tortuga = "renata")

In [104]:
typeof(mismascotas_nt)

NamedTuple{(:perro, :gato, :tortuga), Tuple{String, String, String}}

In [105]:
# recupera elemento por índice
mismascotas_nt[1]

"alpha"

In [106]:
# recupera elemento por el nombre
mismascotas_nt.gato

"yanina"

### Diccionarios

Usualmente los diccionarios se utilizan cuando se tienen dos conjuntos de datos los cuales están interrelacionados. Los diccionarios se construyen usando la función `Dict()`, la inicialización puede ser un diccionario vacío. La sintaxis es:

`Dict(key1 => value1, key2 =>value2, ...)`

Un ejemplo del uso de un diccionario es una lista de contactos que asocia nombre con números telefónicos:

In [107]:
mycontacts = Dict("Jenny" => "867-5309", "Ghostbusters" => "555-2368")

Dict{String, String} with 2 entries:
  "Jenny"        => "867-5309"
  "Ghostbusters" => "555-2368"

In [108]:
# inicializa un diccionario vacío
mydict = Dict()

Dict{Any, Any}()

In [109]:
# indexado por llave
mycontacts["Jenny"]

"867-5309"

In [110]:
# agrega un elemento al diccionario
mycontacts["Chloe"] = "321-7562"

"321-7562"

In [111]:
mycontacts

Dict{String, String} with 3 entries:
  "Jenny"        => "867-5309"
  "Ghostbusters" => "555-2368"
  "Chloe"        => "321-7562"

Para eliminar un elemento del diccionario se utiliza la función `pop!`

In [112]:
pop!(mycontacts, "Ghostbusters")

"555-2368"

In [113]:
mycontacts

Dict{String, String} with 2 entries:
  "Jenny" => "867-5309"
  "Chloe" => "321-7562"

## 4. Arreglos

Un arreglo _Array_ es una estructura de datos que equivale a las listas de Python y a los arreglos de `numpy`.

En Julia los arreglos son estructuras **modificables** (_mutable_) que contiene colecciones de datos ordenados. La construcción de un Array se hace por medio del uso de `[ ]`.

La sintaxis es:

`[item1, item2, ...]`

In [114]:
myfriends = ["Julio", "Marco", "Victor", "Cesar", "Manuel"]

5-element Vector{String}:
 "Julio"
 "Marco"
 "Victor"
 "Cesar"
 "Manuel"

`Array{String, 1}` denota que se trata de un arreglo unidimensional con tipo de datos `string`.

In [115]:
fibonacci  = [1, 1, 2, 3, 5, 8, 13]

7-element Vector{Int64}:
  1
  1
  2
  3
  5
  8
 13

In [116]:
myarray = [1, 1, 2, 3, "cinco", "ocho", "trece"]

7-element Vector{Any}:
 1
 1
 2
 3
  "cinco"
  "ocho"
  "trece"

In [117]:
# indexado del array
myfriends[2]

"Marco"

In [118]:
# modifica el array usando el índice
myfriends[4] = "Héctor"

"Héctor"

In [119]:
myfriends

5-element Vector{String}:
 "Julio"
 "Marco"
 "Victor"
 "Héctor"
 "Manuel"

**Nota:** El indexado en Julia inicia en 1 (_1-based indexing_) que difiere de otros lenguajes como Python.

In [120]:
l = [3, 4, 5]

3-element Vector{Int64}:
 3
 4
 5

In [121]:
typeof(l)

Vector{Int64} (alias for Array{Int64, 1})

In [ ]:
l = [3, 4, 7.5] # promoting to float

In [ ]:
l = [3.,"hello"]

In [ ]:
l = [3.,'a']

In [ ]:
l = [3., 4, "hello", [3, 4]]

La agregación y eleminación de elementos de un array se realiza por medio de las funciones `push!` y  `pop!` respectivamente.

In [ ]:
fibonacci

In [ ]:
# agrega 21 al final del array
push!(fibonacci, 21 )
fibonacci

In [ ]:
# remueve 21, el último elemento del array.
pop!(fibonacci)
fibonacci

Los ejemplos anteriores son arreglos de escalares, sin embargo, los arreglos pueden tener un número arbitrario de dimensiones y pueden almacenar otros arrays.


In [ ]:
favoritos = [["chocolate", "almendras", "pistache"], ["gato", "perro", "patito"]]

In [ ]:
numeros = [[1, 2, 3], [4, 5], [6, 7, 8, 9]]

In [ ]:
numeros = [[1, 2, 3], [4, 5], [6, 7, 8, 9]]

### Indexado
Los índices de los arreglos de Julia comienzan en 1, a diferencia de Python (inician en 0).

In [ ]:
l = [3, 4, "hello"]

In [ ]:
l[1] 

In [ ]:
l[1:2]

In [ ]:
l[2:end] # use 'end' explicitly

In [ ]:
l[1:end-1]

In [ ]:
l[-1]

Los arreglos de Julia, como las listas de Python (aunque diferentes a los arreglos de `numpy`) son dinámicos. Sin embargo, la sintaxis es un poco diferente a la de Python; para agregar un elemento al final de un arreglo, se requiere escribir:

Julia `Arrays`, like Python lists, but unlike `numpy` arrays, are dynamic. However, the syntax is rather different from Python -- to add an element at hte end of the list, we write:

In [ ]:
l = [3, 4, 5]

In [ ]:
l = [3, 4, 5]
push!(l,7)

In [ ]:
l

In [ ]:
l = [3, 4, 5]
l + l

Los `arrays` de Julia son objetos, sin embargo, a diferencia de Python, no tienen métodos implementados. La función `push()` más el signo de admiración `!` denota una convención en Julia que significa que esta función modificará a su argumento. En el ejemplo previo, el objeto `l` se modifica al incluir al final del arreglo el valor `7` 

In [ ]:
push!

In [ ]:
methods(push!)

Dando click al link, podemos enlazarnos al repositorio en github donde está el código del método

In [ ]:
append!(l, [10, 11, 12])

Los siguientes arreglos 2D y 3D son generados con usando números aleatorios:

In [ ]:
rand(4, 3)

In [ ]:
rand(4, 3, 2)

`rand()` genera arreglos con valores aleatorios dentro del rango `[0,1]`

Es posible agregar el rango de elementos a la construcción de un arreglo aleatorio.

In [ ]:
rand(-10:10, 4, 3)

### Copia de arreglos

In [ ]:
fibonacci

In [ ]:
misnumeros = fibonacci

In [ ]:
misnumeros[1] = 50
misnumeros

In [ ]:
fibonacci

Editar la copia de un arreglo modifica el original, esto es que sólo se asigna un nuevo nombre a un arreglo existente .`fibonacci` es modificado al asignar valores a `misnumeros`.

No se hace una copia de `fibonacci`, tan solo se ha creado un nuevo acceso a este arreglo por medio de `misnumeros`. Una copia de un arreglo se hace por medio de la función `copy()`.

In [ ]:
fibonacci[1] = 1
fibonacci

In [ ]:
newnumeros = copy(fibonacci)
newnumeros

In [ ]:
newnumeros[1] = 50
newnumeros

In [ ]:
fibonacci

### Comprehensión de arreglos

Los lenguajes de programación de alto nivel tienen mecanismo muy poderosos para crear arreglos y vectores. 

Vamos a inicializar un arreglo bidimensional y por medio de un ciclo `for` crearemos de *forma tradicional* una tabla de suma (_adition table_) donde cada entrada es la suma de sus correspondientes índices de renglón y columna.

Posteriormente crearemos la misma tabla por medio de una **comprensión de arreglos** (comprensión de listas en Python).

In [1]:
m,n = 5,5
A = fill(0, (m,n))

5×5 Matrix{Int64}:
 0  0  0  0  0
 0  0  0  0  0
 0  0  0  0  0
 0  0  0  0  0
 0  0  0  0  0

In [2]:
for i in 1:m
    for j in 1:n
        A[i,j] = i + j
    end
end
A

5×5 Matrix{Int64}:
 2  3  4  5   6
 3  4  5  6   7
 4  5  6  7   8
 5  6  7  8   9
 6  7  8  9  10

De forma equivalente podemos hacer:

In [ ]:
m,n = 5,5
B = fill(0, (m,n))

In [ ]:
for i in 1:m, j in 1:n
        B[i,j] = i + j
end
B

Crear esta tabla por medio del uso de **comprehensión de arreglos** es una forma Juliana de trabajar los arreglos:

In [3]:
C = [i + j for i in 1:m, j in 1:n]

5×5 Matrix{Int64}:
 2  3  4  5   6
 3  4  5  6   7
 4  5  6  7   8
 5  6  7  8   9
 6  7  8  9  10

Esta comprehensión de arreglos es equivalente a la _comprehensión de listas_ de python

In [4]:
[x for x in 1:15]

15-element Vector{Int64}:
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10
 11
 12
 13
 14
 15

## 5. Operaciones con arreglos

Julia provee diversas operaciones predefinidas para operar sobre arreglos que resultan muy útiles.

In [5]:
a = [1.1, 2.2, 3.3]
b = [4.4, 5.5, 6.6]

3-element Vector{Float64}:
 4.4
 5.5
 6.6

In [6]:
a + b

3-element Vector{Float64}:
 5.5
 7.7
 9.899999999999999

In [7]:
3.5 * a

3-element Vector{Float64}:
  3.8500000000000005
  7.700000000000001
 11.549999999999999

Sin embargo, los operadores, en general, no operan _elemento a elemento_ (como sucedería en `numpy`):

In [8]:
a * b

LoadError: MethodError: no method matching *(::Vector{Float64}, ::Vector{Float64})

Closest candidates are:
  *(::Any, ::Any, ::Any, ::Any...)
   @ Base operators.jl:578
  *(::StridedMatrix{T}, ::StridedVector{S}) where {T<:Union{Float32, Float64, ComplexF64, ComplexF32}, S<:Real}
   @ LinearAlgebra ~/julia-1.9.0/share/julia/stdlib/v1.9/LinearAlgebra/src/matmul.jl:49
  *(::StridedVecOrMat, ::LinearAlgebra.Adjoint{<:Any, <:LinearAlgebra.LQPackedQ})
   @ LinearAlgebra ~/julia-1.9.0/share/julia/stdlib/v1.9/LinearAlgebra/src/lq.jl:269
  ...


No obstante, las operaciones _elemento a elemento_ pueden hacerse tipo sintaxis de _Matlab_ anteponiendo el símbolo `.` al operador:

In [9]:
a.*b

3-element Vector{Float64}:
  4.840000000000001
 12.100000000000001
 21.779999999999998

### Paquetes y funciones predefinidas

Las funciones principales de álgebra lineal pueden invocarse mediante la instalación del paquete `LinearAlgebra`

In [21]:
using Pkg
Pkg.add("LinearAlgebra")
using LinearAlgebra

   Resolving package versions...
  No Changes to `~/.julia/environments/v1.9/Project.toml`
  No Changes to `~/.julia/environments/v1.9/Manifest.toml`


In [22]:
dot(a,b)

38.72

In [23]:
cross(a,b)

3-element Vector{Float64}:
 -3.629999999999999
  7.26
 -3.630000000000001

In [24]:
?cross() #Documentación de cross()

```
cross(x, y)
×(x,y)
```

Compute the cross product of two 3-vectors.

# Examples

```jldoctest
julia> a = [0;1;0]
3-element Vector{Int64}:
 0
 1
 0

julia> b = [0;0;1]
3-element Vector{Int64}:
 0
 0
 1

julia> cross(a,b)
3-element Vector{Int64}:
 1
 0
 0
```


In [25]:
norm(a)

4.115823125451335

In [26]:
?norm()

```
norm(A, p::Real=2)
```

For any iterable container `A` (including arrays of any dimension) of numbers (or any element type for which `norm` is defined), compute the `p`-norm (defaulting to `p=2`) as if `A` were a vector of the corresponding length.

The `p`-norm is defined as

$$
\|A\|_p = \left( \sum_{i=1}^n | a_i | ^p \right)^{1/p}
$$

with $a_i$ the entries of $A$, $| a_i |$ the [`norm`](@ref) of $a_i$, and $n$ the length of $A$. Since the `p`-norm is computed using the [`norm`](@ref)s of the entries of `A`, the `p`-norm of a vector of vectors is not compatible with the interpretation of it as a block vector in general if `p != 2`.

`p` can assume any numeric value (even though not all values produce a mathematically valid vector norm). In particular, `norm(A, Inf)` returns the largest value in `abs.(A)`, whereas `norm(A, -Inf)` returns the smallest. If `A` is a matrix and `p=2`, then this is equivalent to the Frobenius norm.

The second argument `p` is not necessarily a part of the interface for `norm`, i.e. a custom type may only implement `norm(A)` without second argument.

Use [`opnorm`](@ref) to compute the operator norm of a matrix.

# Examples

```jldoctest
julia> v = [3, -2, 6]
3-element Vector{Int64}:
  3
 -2
  6

julia> norm(v)
7.0

julia> norm(v, 1)
11.0

julia> norm(v, Inf)
6.0

julia> norm([1 2 3; 4 5 6; 7 8 9])
16.881943016134134

julia> norm([1 2 3 4 5 6 7 8 9])
16.881943016134134

julia> norm(1:9)
16.881943016134134

julia> norm(hcat(v,v), 1) == norm(vcat(v,v), 1) != norm([v,v], 1)
true

julia> norm(hcat(v,v), 2) == norm(vcat(v,v), 2) == norm([v,v], 2)
true

julia> norm(hcat(v,v), Inf) == norm(vcat(v,v), Inf) != norm([v,v], Inf)
true
```

---

```
norm(x::Number, p::Real=2)
```

For numbers, return $\left( |x|^p \right)^{1/p}$.

# Examples

```jldoctest
julia> norm(2, 1)
2.0

julia> norm(-2, 1)
2.0

julia> norm(2, 2)
2.0

julia> norm(-2, 2)
2.0

julia> norm(2, Inf)
2.0

julia> norm(-2, Inf)
2.0
```


In [27]:
a # vector columna

3-element Vector{Float64}:
 1.1
 2.2
 3.3

In [28]:
transpose(a) # vector renglón

1×3 transpose(::Vector{Float64}) with eltype Float64:
 1.1  2.2  3.3

In [29]:
a' # row vector

1×3 adjoint(::Vector{Float64}) with eltype Float64:
 1.1  2.2  3.3

In [30]:
a

3-element Vector{Float64}:
 1.1
 2.2
 3.3

In [31]:
M = [1 2 3 4] # spaces distribute as row

1×4 Matrix{Int64}:
 1  2  3  4

In [32]:
M = [1, 2, 3, 4] # the comma distribute as column

4-element Vector{Int64}:
 1
 2
 3
 4

In [33]:
M = [[1, 2], [3, 4]] # brackets works as array

2-element Vector{Vector{Int64}}:
 [1, 2]
 [3, 4]

In [34]:
M = reshape([1, 2, 3, 4], (2,2))

2×2 Matrix{Int64}:
 1  3
 2  4

In [35]:
M = [[2, 1]; [3, 1]]

4-element Vector{Int64}:
 2
 1
 3
 1

In [36]:
 M = [1 2 ; 3 4]

2×2 Matrix{Int64}:
 1  2
 3  4

In [37]:
M = [1:8;] # semicolon ; is important ¿por qué?

8-element Vector{Int64}:
 1
 2
 3
 4
 5
 6
 7
 8

In [38]:
M = [1:8;10]

9-element Vector{Int64}:
  1
  2
  3
  4
  5
  6
  7
  8
 10

In [39]:
typeof([1:8;])

Vector{Int64} (alias for Array{Int64, 1})

In [40]:
M = collect(1:8)

8-element Vector{Int64}:
 1
 2
 3
 4
 5
 6
 7
 8

In [41]:
typeof(collect(1:8))

Vector{Int64} (alias for Array{Int64, 1})

In [42]:
? collect()

```
collect(element_type, collection)
```

Return an `Array` with the given element type of all items in a collection or iterable. The result has the same shape and number of dimensions as `collection`.

# Examples

```jldoctest
julia> collect(Float64, 1:2:5)
3-element Vector{Float64}:
 1.0
 3.0
 5.0
```

---

```
collect(collection)
```

Return an `Array` of all items in a collection or iterator. For dictionaries, returns `Pair{KeyType, ValType}`. If the argument is array-like or is an iterator with the [`HasShape`](@ref IteratorSize) trait, the result will have the same shape and number of dimensions as the argument.

Used by comprehensions to turn a generator into an `Array`.

# Examples

```jldoctest
julia> collect(1:2:13)
7-element Vector{Int64}:
  1
  3
  5
  7
  9
 11
 13

julia> [x^2 for x in 1:8 if isodd(x)]
4-element Vector{Int64}:
  1
  9
 25
 49
```


In [43]:
M = reshape([1:8;], (2,2,2))

2×2×2 Array{Int64, 3}:
[:, :, 1] =
 1  3
 2  4

[:, :, 2] =
 5  7
 6  8

In [44]:
a, b

([1.1, 2.2, 3.3], [4.4, 5.5, 6.6])

In [45]:
a ⋅ b # \cdot + <TAB> dot product

38.72

In [46]:
a × b # \times + <TAB> cross product

3-element Vector{Float64}:
 -3.629999999999999
  7.26
 -3.630000000000001

## Ejercicio

Implementar el método Babilonio para calcular la raíz cuadrada de un número entero positivo $y$ por medio de la iteración: $$ x_{n+1}= \frac{1}{2}\left( x_n + \frac{y}{x_n} \right)$$