<img src="img/julia.png" width=150 height=150 />

# Introducción a Julia - Parte 2

## Funciones

Vamos a ver en este apartado:
* Declaración de una función
* _Duck-typing_ en Julia
* Funciones mutables y no mutables
* Funciones de orden superior

### Declaración de una función
Julia permite declarar de diversas formas una función. La primera requiere de la palabra reservada `function` 

In [1]:
function saludo(name)
    println("Hola $name, ¿qué tal estás?")
end

saludo (generic function with 1 method)

In [7]:
function saludo(name, name2)
    println("Hola $name, $name2, ¿qué tal están?")
end

saludo (generic function with 2 methods)

In [45]:
function f(x)
    x^2
end

f (generic function with 1 method)

En la declaración anterior no se especificó la palabra reservada `return` para devolver algún valor de la función. Julia devuelve el resultado de la última sentencia de la función. De cualquier modo se puede especificar el valor de regreso haciéndolo explícito.

In [11]:
function g(x)
    println("El cuadrado de $x es:", x^2)
    return x^2
end

g (generic function with 1 method)

In [5]:
saludo("Oscar") 

Hola Oscar, ¿qué tal estás?


In [8]:
saludo("Oscar", "Susana")

Hola Oscar, Susana, ¿qué tal están?


In [9]:
f(5)

25

In [12]:
g(5)

El cuadrado de 5 es:25


25

In [35]:
m,n = 1000, 2000
[(a,b,c) for a in m:n, b in m:n, c in m:n if (a^2 + b^2 == c^2)]

316-element Vector{Tuple{Int64, Int64, Int64}}:
 (1050, 1000, 1450)
 (1000, 1050, 1450)
 (1071, 1020, 1479)
 (1020, 1071, 1479)
 (1100, 1008, 1492)
 (1008, 1100, 1492)
 (1092, 1040, 1508)
 (1040, 1092, 1508)
 (1131, 1008, 1515)
 (1008, 1131, 1515)
 (1080, 1071, 1521)
 (1071, 1080, 1521)
 (1120, 1035, 1525)
 ⋮
 (1191, 1588, 1985)
 (1140, 1625, 1985)
 (1539, 1260, 1989)
 (1260, 1539, 1989)
 (1592, 1194, 1990)
 (1194, 1592, 1990)
 (1705, 1032, 1993)
 (1032, 1705, 1993)
 (1596, 1197, 1995)
 (1197, 1596, 1995)
 (1600, 1200, 2000)
 (1200, 1600, 2000)

Otra forma de declarar funciones es sin la utilización de las palabras reservadas `function` y  `end`.

In [ ]:
saludo1(name) = println("Hola $name, qué tal!!")

In [ ]:
f1(x) = x

In [ ]:
f1(x) = x^2

In [ ]:
f1(3)

In [ ]:
f1(5)

Este tipo de declaración asemeja más a una sintáxis matemática.

Finalmente, tenemos la siguiente forma de declar una función. El resultado es la declaración de una función **"anónima"**. Este tipo de declaración es similar en concepto al de las funciones lambda.

In [ ]:
name -> println("Hola $name, qué tal!!")

In [ ]:
(name1, name2) -> println("Hola amigos $name1, $name2")

Una función declarada de esta forma carece de nombre y solo tiene la especificación del argumento (s) que recibe, separada del cuerpo de la función por `->`. Pareciera que no hay forma de acceder a una función anónima, sin embargo, funciones que "no tienen nombre" son utilizadas en varios casos específicos como se verá más adelante.

Si se desea utilizar una función anónima es posible asignarla a una variable (_binding_). 

In [ ]:
saludo2 = (name1, name2) -> println("Hola amigos $name1 y $name2")
saludo2("marco", "javier")

In [ ]:
f2 = x -> x^2
f2(5)

### Duck-typing en Julia 

_"Si grazna como pato, mueve la cola como pato, entonces es un pato"_

Las funciones en Julia siempre funcionarán para entradas para las cuales "encuentre sentido"

In [36]:
saludo(3.14159)

Hola 3.14159, ¿qué tal estás?


Las función `saludo()` funciona para un número real

In [46]:
f("hola")

"holahola"

In [47]:
A = rand(1:3,(3,3))
A

3×3 Matrix{Int64}:
 3  3  3
 3  1  3
 3  1  1

In [48]:
f(A)

3×3 Matrix{Int64}:
 27  15  21
 21  13  15
 15  11  13


La función `f` funciona para enteros, reales o una matriz. También funcionará para una cadena de caracteres pues el operador `^` opera para strings.

In [ ]:
f("hi")

Por otra parte, la función f no funcionará con un vector como argumento puesto que `v^2` no es una operación algebráica que esté definida, a diferencia de `A^2` que sí lo es.

In [ ]:
v = rand(3)

In [ ]:
f(v)

### Funciones Mutables vs No Mutables 

Por convención, funciones seguidas de `!` alteran sus contenidos y funciones que no lo tienen no pueden modificarlos.

In [ ]:
v = [3, 5, 2]

In [ ]:
sort(v)

In [ ]:
v

`sort(v)` devuelve un arrego ordenado que contiene los mismos elementos de `v` sin alterar a `v`.

In [ ]:
sort!(v)

In [ ]:
v

`sort!(v)` es altera el argumento `v` que se le pasa a la función.

### Funciones de orden superior 

La función `map()` es una función en Julia que toma como uno de sus argumentos de entrada una _función_. `map()` aplica la función a cada elemento de la estructura de datos que se le pasa.

Por ejemplo, al ejecutar:
```julia
map(f,[1, 2, 3])
```
obtendremos un arreglo de salida donde la función `f()` se aplica a cada uno de los elementos del array `[1, 2, 3]`, es decir,
```julia
[f(1), f(2), f(3)]

In [ ]:
map(f,[1, 2, 3])

Se han elevado al cuadrado todos los elementos de `[1, 2, 3]` en lugar de elevar al cuadrado el vector mismo. Para hacer esto, se puede pasar a la función `map()` una función anónima en lugar del nombre de la función:

In [ ]:
myfunc = x -> x^3

In [ ]:
map(myfunc, [1,2,3])

In [ ]:
map(x -> x^3, [1, 2, 3])

Podemos hacer la operación de **Broadcast** para una función, esto es una "expansión la dimensión unaria" de los objetos que se pasan a la función.

Apliquemos `f()` a una matriz `A` y veamos la diferencia al hacer un _broadcast_ a `f()` sobre `A`

In [ ]:
A = [i + 3*j for j in 0:2, i in 1:3]

In [ ]:
f(A)

Esto es:
```julia
f(A) = A^2 = A * A
```

In [ ]:
f.(A)

Con el _broadcast_ cada elemento de `A` se elevan al cuadrado

La notación con `.` para hacer el _broadcast_ permite escribir composiciones complejas de expresiones en una manera que parece más natural y cercana a la notación matemática convencional.

In [ ]:
A

Podemos operar de la siguiente manera:

In [ ]:
A .+ 2 .* f.(A) ./ A

### Operadores como funciones

In [ ]:
3 + 4

In [ ]:
+(3,4)

In [ ]:
3 // 4

In [ ]:
//(3,4)

In [ ]:
// 

In [ ]:
methods(//)

Este es el comienzo de lo que se llamaremos **despacho múltiple**. Estamos definiendo una versión o método de esta función la cual acepta argumentos de diferentes tipos, en este caso hay ocho combinaciones diferentes de tipos que podemos usar.

En general, las funciones se implementan especificando la acción que llevará acabo sobre diferentes tipos de datos.

En las **funciones genéricas** no se especifica qué tipo de dato aceptan, al igual que en Python funcionarán siempre que las operaciones realizadas en ellas tengan sentido para el valor de entrada.

In [ ]:
duplicate(x) = x^2

In [ ]:
duplicate(3)

In [ ]:
duplicate(3.5)

In [ ]:
 duplicate("hola")

Notemos que la concatenación de cadena utiliza el operador `*`, en lugar del operador `+` como se hace en Python. 

Repetir una cadena entonces es equivalente a aplicar una potencia a un valor entero.

In [ ]:
"hello" ^ 2  #duplica

In [ ]:
"hello " * "world" #concatena

In [ ]:
"hello " + "world" #error

El **operador suma no esta definida par las cadenas**. ¿Para cuáles tipos de datos está definida?

In [ ]:
+

Podemos ver que `+` es tratado como una función y tiene múltiple métodos implementados, los cuales en Julia son considerados como **versiones especializadas** de dicha función para que actúen sobre diferentes tipos de datos:

In [ ]:
methods(+)

Si no deseáramos utilizar el operador `*` para la concatenación de cadenas, podríamos **definir nuestro propio** operador `+` para la concatenación de cadenas: 

In [ ]:
import Base.+

In [ ]:
string("hola", "crayola")

In [ ]:
+(s1::String, s2::String) = string(s1,s2)

In [ ]:
"Hola" + "Crayola"

A partir de la versión v1.0 es necesario importar explícitamente `Base.x` para extender el método `x`. `Base` es un módulo general en el que se incluyen diversos operadores.

In [ ]:
"El valor de x es:" + 3

In [ ]:
3 + "HOLA"

**Ejercio:** Definamos un método del operador `+` para que concatene una caden y un número.

In [ ]:
+(s::String, x::Number) = s + "$x"

In [ ]:
"El valor de x es: " + 3

In [ ]:
"El valor de x es: " + 3.5

In [ ]:
"El valor de x es: " + 3

In [ ]:
3 + "Hola" #redefinir +

In [ ]:
"Complex" + (3 + im)

In [ ]:
"Cadena" .+ [3,4,5]

### Ejercicio

Utiliza el "método de la potencia" para calcular el igenvalor $\lambda_1$ mas grande asociado a la matriz: 
$$ M =\begin{pmatrix}
4 & -5 \\ 
2 & -3
\end{pmatrix}$$

El método consiste en inciar con un vector no cero arbitrario $\mathbf{w}$ y repetidamente multiplicarlo por $M$, con lo que se calcularán potencias de la matriz $M$ multiplicados por $\mathbf{w}$. El resultado converge al eigenvector $\mathbf{v_1}$ correspondiente a $\mathbf{\lambda_1}$

Una forma de resolver el problema es la siguiente:

In [ ]:
using LinearAlgebra

In [ ]:
w = [1., 0]
M = reshape([4., 2, -5,  -3],(2,2))
M, w

In [ ]:
w0 = [1., 0]
w = w0

for i in 1:10
    Mw = M * w
    println("Prod: ", Mw)
    println("maximum: ", maximum(Mw))
    w_new = Mw / maximum(Mw)
    println("w_new: ",  w_new)
    println("error: ", norm(w_new - w))
    w = w_new
    
end

In [ ]:
Mw = M * w

In [ ]:
eigvals(M)

Otra forma de implementación, será por medio del uso de un criterio de paro para el algoritmo:

In [ ]:
w0 = [1., 0]
w = w0
w_new = [1, 1]

tolerance = 1e-10
err = norm(w_new - w)

while err > tolerance
    Mw = M * w
    println("Prod: ", Mw)
    println("maximum: ", maximum(Mw))
    w_new = (Mw)/ maximum(Mw)
    println("w_new: ",  w_new)
    err = norm(w_new - w)
    println("error: ", err)
    w = w_new
end

In [ ]:
Mw = M * w

## Tipos de datos definidos por el usuario

Un tipo de **dato definido por el usuario** ([_composite types_](https://docs.julialang.org/en/v1/manual/types/#Composite-Types)) es una colección de datos. A diferencia de Python, estos tipos no tienen sus propios métodos (funciones internas del tipo).

Los métodos son definidos de forma separada y están caracterizados por _todos_ y cada uno de los tipos de sus argumentos, esto es conocido como **despacho múltiple** (_multiple dispatch_). Nos referiremos a _despacho_ como el proceso de elegir la "versión" adecuada para que ejecute una función.

Un ejemplos sencillo y útil es la definición de un tipo de dato **vector 2D** (vease también el paquete `InmutableArrays.jl`, los arreglos de tamaño fijo han sido incorporados dentro de `Base` de Julia) 

In [ ]:
typeof(3 // 4)

In [ ]:
@which 3//4

In [ ]:
Rational(3)

Vamos a definir el tipo **Vector2D**

In [51]:
struct Vector2D
    x::Float64
    y::Float64
end

Utilizamos `struct` empaquetar el objeto y almacenarlo de manera eficiente

In [52]:
methods(Vector2D)

# 2 methods for type constructor:
 [1] Vector2D(x::Float64, y::Float64)
     @ In[51]:2
 [2] Vector2D(x, y)
     @ In[51]:2

`struct`define por defecto un tipo de [dato inmutable](https://docs.julialang.org/en/v1/base/base/#struct).

Una instancia de este tipo de dato no puede ser modificada después de su construcción. En cambio, usar un `mutable struct` declara un tipo cuyas instancias pueden ser modificadas. Tipos inmutables evitan manipular individualmente los elementos del objeto, tipos mutables permiten manipulaciones.

Los datos almacenados en objetos inmutables están **colocados consecutivamente en memoria** -en lugar de estar en una caja- por lo que no hay punteros al objeto, esto permite mayor velocidad de acceso al objeto; el objeto está almacenado en una forma empaquetada eficiente.

### Definición de operaciones para datos definidos por el usuario

In [53]:
v = Vector2D(3,4)

Vector2D(3.0, 4.0)

In [54]:
typeof(v)

Vector2D

In [55]:
v1 = Vector2D(3., 2.)

Vector2D(3.0, 2.0)

In [56]:
v2 = Vector2D(3., 2)

Vector2D(3.0, 2.0)

In [57]:
v3 = Vector2D(3, 2.)

Vector2D(3.0, 2.0)

In [58]:
v4 = Vector2D(1 + 3im, 2 + im)

LoadError: InexactError: Float64(1 + 3im)

In [ ]:
typeof(Vector2D)

In [ ]:
fieldnames(Vector2D)

### Ejercicios

- Definir algún otra operacion matemáticas sobre objetos de tipo `Vector2D`.
- Definir una **Partícula** con posición y velocidad en 2D.
- Definir la función `move` que actua sobre la Partícula para moverla cada determinado tiempo $\delta t$.

In [ ]:
v = Vector2D(3,4)
w = Vector2D(5,6)
v + w

In [ ]:
+(v::Vector2D, w::Vector2D) = Vector2D(v.x + w.x, v.y + w.y)

In [ ]:
v + w

In [ ]:
v + w + v

In [ ]:
v * 5

In [ ]:
import Base.*

In [ ]:
methods(*)

In [ ]:
*(v::Vector2D, α::Number) = Vector2D(v.x * α, v.y * α) 

In [ ]:
v * 5

In [ ]:
 v + w * 2 

Ahora deseamos mostrar un objeto de tipo `Vector2D` con un formato particular:

In [ ]:
print(v)

En Python, esto se logra mediante la sobrecarga del método `__repr__`, en Julia tendremos que extender el método `show`:

In [ ]:
show

In [ ]:
import Base.show

In [ ]:
show(io::IO, v::Vector2D) = print(io, "[$(v.x), $(v.y)]")

In [ ]:
v

In [ ]:
print(v)